name: app
description: A new Flutter project.
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter

  dart_mqtt: ^1.0.2+4

  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6

  google_fonts: ^3.0.1

  http: ^0.13.5

  ionicons: ^0.2.1
  line_icons: ^2.0.1 

  mqtt_client: ^9.7.4  
  mqtt5_client: ^3.3.4 
  
  speech_to_text: ^6.1.0

  cupertino_icons: ^1.0.2 
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true

  assets: 
    - assets/cert/awsiotca.pem 
    - assets/cert/test001a.private.key
    - assets/cert/test001a.cert.pem
    - .env 